name: build

on:
  pull_request:
  push:
    # branches:
    #   - master
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install DeepXDE with requirements
        run: python -m pip install -e .

      - name: List environment
        run: python -m pip freeze

      - name: Test build with TensorFlow v1
        env:
          DDE_BACKEND: tensorflow.compat.v1
        run: |
          python -m pip install tensorflow
          python -c "import deepxde"

      - name: Test build with TensorFlow
        env:
          DDE_BACKEND: tensorflow
        run: |
          python -m pip install tensorflow-probability
          python -c "import deepxde"

      - name: Test build with PyTorch
        env:
          DDE_BACKEND: pytorch
        run: |
          python -m pip install torch
          python -c "import deepxde"

      - name: Test build with Jax
        if: matrix.os != 'windows-latest'   # jaxlib is not available on windows
        env:
          DDE_BACKEND: jax
        run: |
          python -m pip install jax flax optax
          python -c "import deepxde"

      # DeepXDE does not work with stable paddle, and building paddle from source will
      # take a lot of CI time, slowing the development process
      #
      # - name: Test build with Paddle
      #   if: matrix.python-version != 3.11   # not available on Python 3.11
      #   run: |
      #     python -m pip install paddlepaddle
      #     DDE_BACKEND=paddle python -c "import deepxde"
      #   env:
      #     DDE_BACKEND: paddle
