name: build

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  import:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install DeepXDE with requirements
        run: python -m pip install -e .

      - name: List environment
        run: python -m pip freeze

      - name: Test build with TensorFlow v1
        env:
          DDE_BACKEND: tensorflow.compat.v1
        run: |
          python -m pip install tensorflow
          python -c "import deepxde"

      - name: Test build with TensorFlow
        env:
          DDE_BACKEND: tensorflow
        run: |
          python -m pip install tensorflow-probability[tf]
          python -c "import deepxde"

      - name: Test build with PyTorch
        env:
          DDE_BACKEND: pytorch
        run: |
          python -m pip install torch
          python -c "import deepxde"

      - name: Test build with Jax
        if: matrix.os != 'windows-latest'  # jaxlib is not available on windows
        env:
          DDE_BACKEND: jax
        run: |
          python -m pip install jax flax optax
          python -c "import deepxde"

      - name: Test build with Paddle
        env:
          DDE_BACKEND: paddle
        run: |
          python -m pip install paddlepaddle==2.6.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
          python -c "import deepxde"
